// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzhycvfqlbdmldxfwaco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6aHljdmZxbGJkbWxkeGZ3YWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDYyNjMsImV4cCI6MjA2NTU4MjI2M30.nndek1KjDVmtpwnW6a-IpKiW4X5yBV17l2XP6pErKbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);